import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.students': 'Students',
    'nav.staff': 'Staff',
    'nav.academics': 'Academics',
    'nav.attendance': 'Attendance',
    'nav.fees': 'Fees',
    'nav.examinations': 'Examinations',
    'nav.documents': 'Documents',
    'nav.idCards': 'ID Cards',
    'nav.library': 'Library',
    'nav.health': 'Health',
    'nav.hostel': 'Hostel',
    'nav.transport': 'Transport',
    'nav.timetable': 'Timetable',
    'nav.communication': 'Communication',
    'nav.announcements': 'Announcements',
    'nav.admissions': 'Admissions',
    'nav.reports': 'Reports',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.account': 'Account',
    'nav.billing': 'Billing',
    'nav.logout': 'Logout',
    'nav.myClasses': 'My Classes',
    'nav.leaveManagement': 'Leave Management',
    'nav.childProfile': 'Child Profile',
    'nav.notifications': 'Notifications',
    'nav.infrastructure': 'Infrastructure',
    'nav.alumni': 'Alumni',
    'nav.visitorManagement': 'Visitor Management',
    'nav.wallet': 'Wallet',
    'nav.schoolConnect': 'School Connect',
    'nav.preferences': 'Preferences',
    'nav.preferencesDesc': 'Customize your personal preferences and appearance.',
    'nav.permissionsManager': 'Permissions Manager',
    
    // Login & Auth
    'auth.signIn': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterCredentials': 'Enter your credentials to access the system',
    'auth.demoCredentials': 'Demo Credentials (Click to use)',
    'auth.allDemoPassword': 'All demo accounts use password: "password"',
    'auth.superAdminAccess': 'Super Admin Access →',
    'auth.welcome': 'Welcome to',
    'auth.signInAccess': 'Sign in to access your dashboard',
    'auth.enterPassword': 'Enter your password',
    'auth.emailPlaceholder': 'your.email@school.edu',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Vitana School Management',
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.welcomeUser': 'Welcome',
    'dashboard.totalStudents': 'Total Students',
    'dashboard.totalStaff': 'Total Staff',
    'dashboard.todayAttendance': "Today's Attendance",
    'dashboard.pendingFees': 'Pending Fees',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.myAssignedClasses': 'My Assigned Classes',
    'dashboard.classesToday': 'Classes Today',
    'dashboard.studentHighlights': 'Student Highlights',
    'dashboard.messages': 'Messages',
    'dashboard.applyLeave': 'Apply Leave',
    'dashboard.myClasses': 'My Classes',
    'dashboard.gradeAssignments': 'Grade Assignments',
    'dashboard.sendMessage': 'Send Message',
    'dashboard.trackProgress': 'Track your child\'s academic progress and school activities.',
    'dashboard.teachingSchedule': 'Your teaching schedule and important updates for today.',
    'dashboard.recentGrades': 'Recent Grades',
    'dashboard.achievementsTitle': 'Achievements',
    'dashboard.contactClassTeacher': 'Contact Class Teacher',
    'dashboard.attendance': 'Attendance',
    'dashboard.lastExamGrade': 'Last Exam Grade',
    'dashboard.unreadMessages': 'Unread Messages',
    'dashboard.scheduled': 'scheduled',
    'dashboard.thisWeek': 'this week',
    'dashboard.thisMonth': 'this month',
    'dashboard.improvement': 'improvement',
    'dashboard.newToday': 'new today',
    'dashboard.achievementsCount': 'achievements',
    'dashboard.unread': 'unread',
    'dashboard.dueDate': 'due date: 30th',
    'dashboard.active': 'Active',
    
    // Common
    'common.search': 'Search',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.class': 'Class',
    'common.section': 'Section',
    'common.subject': 'Subject',
    'common.view': 'View',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.filter': 'Filter',
    'common.total': 'Total',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.close': 'Close',
    'common.manage': 'Manage',
    'common.back': 'Back',
    'common.deactivate': 'Deactivate',
    'common.reactivate': 'Reactivate',
    'common.reason': 'Reason',
    'common.uploadPhoto': 'Upload Photo',
    'common.warning': 'Warning',
    'common.generateTC': 'Generate TC',
    'common.reportCard': 'Report Card',
    'common.preview': 'Preview',
    'common.previewDesc': 'Preview the document before printing or downloading',
    'common.permissions': 'Permissions',
    'common.store': 'Store',
    'common.inventory': 'Inventory',
    'common.sales': 'Sales',
    'common.lowStock': 'Low Stock',
    
    // Permissions Manager
    'permissions.title': 'Permissions Manager',
    'permissions.description': 'Manage access permissions and roles',
    'permissions.moduleAccess': 'Module Access',
    'permissions.roleManagement': 'Role Management',
    'permissions.module': 'Module',
    'permissions.enabled': 'Enabled',
    'permissions.disabled': 'Disabled',
    'permissions.read': 'View',
    'permissions.write': 'Edit',
    'permissions.delete': 'Delete',
    'permissions.saveChanges': 'Save Changes',
    'permissions.success': 'Success',
    'permissions.updated': 'Permissions updated successfully',
    'permissions.error': 'Error',
    'permissions.updateFailed': 'Failed to update permissions',
    'permissions.noChanges': 'No changes to save',
    'permissions.viewAccess': 'View Access',
    'permissions.editAccess': 'Edit Access',
    'permissions.deleteAccess': 'Delete Access',
    
    // Store Manager
    'store.title': 'Store Management',
    'store.description': 'Manage inventory, sales, and store operations',
    'store.inventory': 'Inventory',
    'store.sales': 'Sales',
    'store.lowStock': 'Low Stock Alerts',
    'store.addItem': 'Add Item',
    'store.addSale': 'Add Sale',
    'store.itemName': 'Item Name',
    'store.category': 'Category',
    'store.price': 'Price',
    'store.stock': 'Stock',
    'store.reorderLevel': 'Reorder Level',
    'store.sku': 'SKU',
    'store.totalValue': 'Total Inventory Value',
    'store.totalSales': 'Total Sales',
    'store.lowStockItems': 'Low Stock Items',
    'store.searchItems': 'Search items...',
    'store.allCategories': 'All Categories',
    'store.uniform': 'Uniform',
    'store.books': 'Books',
    'store.stationery': 'Stationery',
    'store.quantity': 'Quantity',
    'store.paymentMethod': 'Payment Method',
    'store.cash': 'Cash',
    'store.card': 'Card',
    'store.upi': 'UPI',
    'store.customerName': 'Customer Name',
    'store.customerPhone': 'Customer Phone',
    'store.saleDate': 'Sale Date',
    'store.items': 'Items',
    'store.total': 'Total',
    'store.viewReceipt': 'View Receipt',
    'store.editSale': 'Edit Sale',
    'store.deleteSale': 'Delete Sale',
    'store.saleAdded': 'Sale added successfully',
    'store.itemAdded': 'Item added successfully',
    'store.itemUpdated': 'Item updated successfully',
    'store.itemDeleted': 'Item deleted successfully',
    
    // Student Profile Page
    'studentProfilePage.title': 'Student Profile',
    'studentProfilePage.completeInfo': 'Complete student information and records',
    'studentProfilePage.back': 'Back',
    'studentProfilePage.editProfile': 'Edit Profile',
    'studentProfilePage.deactivate': 'Deactivate',
    'studentProfilePage.reactivate': 'Reactivate',
    'studentProfilePage.personalDetails': 'Personal Details',
    'studentProfilePage.academicDetails': 'Academic Details',
    'studentProfilePage.guardianDetails': 'Guardian Details',
    'studentProfilePage.uploadPhoto': 'Upload Recent Photo',
    'studentProfilePage.rollNo': 'Roll No',
    'studentProfilePage.dateOfBirth': 'Date of Birth',
    'studentProfilePage.category': 'Category',
    'studentProfilePage.classSection': 'Class & Section',
    'studentProfilePage.admissionDate': 'Admission Date',
    'studentProfilePage.previousSchool': 'Previous School',
    'studentProfilePage.guardianName': 'Guardian Name',
    'studentProfilePage.loadingProfile': 'Loading student profile...',
    'studentProfilePage.studentNotFound': 'Student not found',
    'studentProfilePage.backToStudents': 'Back to Students',
    'studentProfilePage.photoUpdated': 'Photo updated',
    'studentProfilePage.photoSavedSuccess': 'Student photo saved successfully',
    'studentProfilePage.uploadFailed': 'Upload failed',
    'studentProfilePage.couldNotSavePhoto': 'Could not save photo',
    'studentProfilePage.successTitle': 'Success',
    'studentProfilePage.errorTitle': 'Error',
    'studentProfilePage.failedToLoad': 'Failed to load student profile',
    'studentProfilePage.deactivatedSuccess': 'Student deactivated successfully',
    'studentProfilePage.reactivatedSuccess': 'Student reactivated successfully',
    'studentProfilePage.failedToUpdate': 'Failed to update student status',
    'studentProfilePage.attendance': 'Attendance',
    'studentProfilePage.academicPerformance': 'Academic Performance',
    'studentProfilePage.communication': 'Communication',
    'studentProfilePage.documents': 'Documents',
    'studentProfilePage.awards': 'Awards & Achievements',
    'studentProfilePage.fee': 'Fee',

    // Staff Profile Page
    'staffProfilePage.title': 'Staff Profile',
    'staffProfilePage.completeInfo': 'Complete staff information and records',
    'staffProfilePage.back': 'Back',
    'staffProfilePage.editProfile': 'Edit Profile',
    'staffProfilePage.deactivate': 'Deactivate',
    'staffProfilePage.reactivate': 'Reactivate',
    'staffProfilePage.personalDetails': 'Personal Details',
    'staffProfilePage.professionalDetails': 'Professional Details',
    'staffProfilePage.contactInfo': 'Contact Information',
    'staffProfilePage.uploadPhoto': 'Upload Recent Photo',
    'staffProfilePage.phone': 'Phone',
    'staffProfilePage.email': 'Email',
    'staffProfilePage.designation': 'Designation',
    'staffProfilePage.department': 'Department',
    'staffProfilePage.experience': 'Experience',
    'staffProfilePage.years': 'years',
    'staffProfilePage.address': 'Address',
    'staffProfilePage.emergencyContact': 'Emergency Contact',
    'staffProfilePage.classes': 'Classes',
    'staffProfilePage.attendance': 'Attendance',
    'staffProfilePage.payroll': 'Payroll',
    'staffProfilePage.documents': 'Documents',
    'staffProfilePage.certificates': 'Certificates',
    'staffProfilePage.performance': 'Performance',
    'staffProfilePage.assignedClasses': 'Assigned Classes',
    'staffProfilePage.class': 'Class',
    'staffProfilePage.subject': 'Subject',
    'staffProfilePage.students': 'Students',
    'staffProfilePage.viewDetails': 'View Details',
    'staffProfilePage.attendanceRecord': 'Attendance Record',
    'staffProfilePage.loadingProfile': 'Loading staff profile...',
    'staffProfilePage.staffNotFound': 'Staff member not found',
    'staffProfilePage.backToStaff': 'Back to Staff',
    'staffProfilePage.photoUpdated': 'Photo updated',
    'staffProfilePage.photoSavedSuccess': 'Staff photo saved successfully',
    'staffProfilePage.uploadFailed': 'Upload failed',
    'staffProfilePage.couldNotSavePhoto': 'Could not save photo',
    'staffProfilePage.successTitle': 'Success',
    'staffProfilePage.errorTitle': 'Error',
    'staffProfilePage.failedToLoad': 'Failed to load staff profile',
    'staffProfilePage.deactivatedSuccess': 'Staff deactivated successfully',
    'staffProfilePage.reactivatedSuccess': 'Staff reactivated successfully',
    'staffProfilePage.failedToUpdate': 'Failed to update staff status',

    // Student Profile Drawer
    'studentProfile.title': 'Student Profile',
    'studentProfile.rollNo': 'Roll No',
    'studentProfile.classSection': 'Class & Section',
    'studentProfile.dob': 'DOB',
    'studentProfile.guardian': 'Guardian',
    'studentProfile.guardianPhone': 'Guardian Phone',
    'studentProfile.address': 'Address',
    'studentProfile.category': 'Category',
    'studentProfile.admissionDate': 'Admission Date',
    'studentProfile.previousSchool': 'Previous School',
    'studentProfile.reactivateWarning': 'Reactivating will admit the student again. Are you sure you want to proceed?',
    
    // Staff Profile
    'staffProfile.title': 'Staff Profile',
    'staffProfile.designation': 'Designation',
    'staffProfile.department': 'Department',
    'staffProfile.subjects': 'Subjects',
    'staffProfile.joiningDate': 'Joining Date',
    'staffProfile.contact': 'Contact',
    'staffProfile.phone': 'Phone',
    'staffProfile.email': 'Email',
    'staffProfile.address': 'Address',
    'staffProfile.payroll': 'Payroll',
    'staffProfile.leaveManagement': 'Leave Management',
    'staffProfile.performanceTracking': 'Performance Tracking',
    'staffProfile.classesAssigned': 'Classes Assigned',
    'staffProfile.noPayrollRecords': 'No payroll records.',
    'staffProfile.noLeaveRecords': 'No leave records.',
    'staffProfile.noPerformanceRecords': 'No performance records.',
    'staffProfile.active': 'Active',
    'staffProfile.inactive': 'Inactive',
    'staffProfile.inactiveMessage': 'This staff member is currently inactive.',
    
    // Payroll
    'payroll.month': 'Month',
    'payroll.basic': 'Basic',
    'payroll.allowances': 'Allowances',
    'payroll.deductions': 'Deductions',
    'payroll.netPay': 'Net Pay',
    'payroll.status': 'Status',
    'payroll.pending': 'Pending',
    'payroll.paid': 'Paid',
    'payroll.save': 'Save',
    'payroll.saving': 'Saving...',
    
    // Leave
    'leave.type': 'Type',
    'leave.from': 'From',
    'leave.to': 'To',
    'leave.status': 'Status',
    'leave.reason': 'Reason',
    'leave.approved': 'Approved',
    'leave.rejected': 'Rejected',
    
    // Performance
    'performance.year': 'Year',
    'performance.rating': 'Rating',
    'performance.remarks': 'Remarks',
    
    // Student List
    'studentList.title': 'Students',
    'studentList.subtitle': 'Manage student information and records',
    'studentList.filters': 'Filters & Search',
    'studentList.searchPlaceholder': 'Search by name or roll number...',
    'studentList.allClasses': 'All Classes',
    'studentList.class': 'Class',
    'studentList.allSections': 'All Sections',
    'studentList.section': 'Section',
    'studentList.clearFilters': 'Clear Filters',
    'studentList.showing': 'Showing',
    'studentList.of': 'of',
    'studentList.students': 'students',
    'studentList.rollNo': 'Roll No',
    'studentList.name': 'Name',
    'studentList.guardianName': 'Guardian Name',
    'studentList.contact': 'Contact',
    'studentList.status': 'Status',
    'studentList.actions': 'Actions',
    'studentList.loading': 'Loading students...',
    'studentList.noStudentsFound': 'No students found',
    'studentList.adjustCriteria': 'Try adjusting your search criteria',
    'studentList.addFirstStudent': 'Add First Student',
    
    // Staff List
    'staffList.title': 'Staff Management',
    'staffList.addStaff': 'Add Staff',
    'staffList.directory': 'Staff Directory',
    'staffList.searchPlaceholder': 'Search staff...',
    'staffList.filter': 'Filter',
    'staffList.name': 'Name',
    'staffList.designation': 'Designation',
    'staffList.department': 'Department',
    'staffList.contact': 'Contact',
    'staffList.status': 'Status',
    'staffList.actions': 'Actions',
    'staffList.noStaffFound': 'No staff found.',
    
    // Child Profile
    'childProfile.title': 'My Child',
    'childProfile.studentId': 'Student ID',
    'childProfile.overallGrade': 'Overall Grade',
    'childProfile.attendance': 'Attendance',
    'childProfile.overview': 'Overview',
    'childProfile.subjects': 'Subjects',
    'childProfile.recentGrades': 'Recent Grades',
    'childProfile.profileDetails': 'Profile Details',
    'childProfile.academicPerformance': 'Academic Performance',
    'childProfile.classRank': 'Class Rank',
    'childProfile.attendanceRate': 'Attendance Rate',
    'childProfile.thisWeek': 'This Week',
    'childProfile.mathTest': 'Math Test',
    'childProfile.tomorrow': 'Tomorrow',
    'childProfile.scienceProject': 'Science Project Due',
    'childProfile.friday': 'Friday',
    'childProfile.ptMeeting': 'Parent-Teacher Meeting',
    'childProfile.saturday': 'Saturday',
    'childProfile.subjectPerformance': 'Subject Performance',
    'childProfile.teacher': 'Teacher',
    'childProfile.currentGrade': 'Current Grade',
    'childProfile.subject': 'Subject',
    'childProfile.assessment': 'Assessment',
    'childProfile.grade': 'Grade',
    'childProfile.date': 'Date',
    'childProfile.studentProfile': 'Student Profile',
    'childProfile.editContactInfo': 'Edit Contact Info',
    'childProfile.editContactTitle': 'Edit Contact Information',
    'childProfile.phoneNumber': 'Phone Number',
    'childProfile.emailAddress': 'Email Address',
    'childProfile.address': 'Address',
    'childProfile.updateContact': 'Update Contact Information',
    'childProfile.fullName': 'Full Name',
    'childProfile.dateOfBirth': 'Date of Birth',
    'childProfile.bloodGroup': 'Blood Group',
    'childProfile.admissionDate': 'Admission Date',
    'childProfile.contactInformation': 'Contact Information',
    'childProfile.successTitle': 'Success',
    'childProfile.successMessage': 'Contact information updated successfully',
    
    // Settings
    'settings.title': 'Settings',
    'settings.description': 'App settings and preferences.',
    'settings.theme': 'Theme',
    'settings.systemDefault': 'System Default',
    'settings.enabled': 'Enabled',
    'settings.general': 'General',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.english': 'English',
    'settings.hindi': 'हिंदी',
    'settings.selectTheme': 'Select Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.backup': 'Backup',
    'settings.biometric': 'Biometric Management',
    'settings.import': 'Data Import',
    
    // Students
    'students.title': 'Students Management',
    'students.addStudent': 'Add Student',
    'students.studentList': 'Student List',
    'students.rollNo': 'Roll No',
    'students.guardian': 'Guardian',
    'students.admissionDate': 'Admission Date',
    'students.totalStudents': 'Total Students',
    'students.studentDetails': 'Student Details',
    'students.personalInfo': 'Personal Information',
    'students.academicInfo': 'Academic Information',
    'students.contactInfo': 'Contact Information',
    'students.emergencyContact': 'Emergency Contact',
    'students.medicalInfo': 'Medical Information',
    'students.transportInfo': 'Transport Information',
    'students.feeStatus': 'Fee Status',
    'students.attendanceRecord': 'Attendance Record',
    'students.examResults': 'Exam Results',
    'students.disciplinaryRecord': 'Disciplinary Record',
    'students.achievements': 'Achievements',
    'students.documents': 'Documents',
    'students.bloodGroup': 'Blood Group',
    'students.allergies': 'Allergies',
    'students.specialNeeds': 'Special Needs',
    'students.parentOccupation': 'Parent Occupation',
    'students.annualIncome': 'Annual Income',
    'students.caste': 'Caste',
    'students.religion': 'Religion',
    'students.nationality': 'Nationality',
    
    // Staff
    'staff.title': 'Staff Management',
    'staff.addStaff': 'Add Staff',
    'staff.staffList': 'Staff List',
    'staff.designation': 'Designation',
    'staff.department': 'Department',
    'staff.joiningDate': 'Joining Date',
    'staff.totalStaff': 'Total Staff',
    'staff.staffDetails': 'Staff Details',
    'staff.personalInfo': 'Personal Information',
    'staff.professionalInfo': 'Professional Information',
    'staff.contactInfo': 'Contact Information',
    'staff.emergencyContact': 'Emergency Contact',
    'staff.bankDetails': 'Bank Details',
    'staff.qualifications': 'Qualifications',
    'staff.experience': 'Experience',
    'staff.salary': 'Salary',
    'staff.allowances': 'Allowances',
    'staff.deductions': 'Deductions',
    'staff.workingHours': 'Working Hours',
    'staff.leaveBalance': 'Leave Balance',
    'staff.performanceRating': 'Performance Rating',
    'staff.training': 'Training',
    'staff.certifications': 'Certifications',
    'staff.employeeId': 'Employee ID',
    'staff.subjectsTaught': 'Subjects Taught',
    'staff.classesAssigned': 'Classes Assigned',
    'staff.teachingLoad': 'Teaching Load',
    'staff.extraCurricular': 'Extra Curricular Activities',
    
    // Attendance
    'attendance.title': 'Attendance Management',
    'attendance.markAttendance': 'Mark Attendance',
    'attendance.present': 'Present',
    'attendance.absent': 'Absent',
    'attendance.late': 'Late',
    'attendance.excused': 'Excused',
    'attendance.attendanceReport': 'Attendance Report',
    
    // Academic
    'academic.title': 'Academic Management',
    'academic.academicYear': 'Academic Year',
    'academic.classes': 'Classes',
    'academic.subjects': 'Subjects',
    'academic.syllabus': 'Syllabus',
    'academic.results': 'Results',
    
    // Fees & Payments
    'fees.title': 'Fee Management',
    'fees.payNow': 'Pay Now',
    'fees.feeSummary': 'Fee Summary',
    'fees.totalFees': 'Total Fees',
    'fees.pending': 'Pending',
    'fees.nextDue': 'Next Due',
    'fees.viewDetails': 'View Details',
    'fees.feeStructure': 'Fee Structure',
    'fees.tuitionFee': 'Tuition Fee',
    'fees.admissionFee': 'Admission Fee',
    'fees.examFee': 'Exam Fee',
    'fees.libraryFee': 'Library Fee',
    'fees.transportFee': 'Transport Fee',
    'fees.hostelFee': 'Hostel Fee',
    'fees.developmentFee': 'Development Fee',
    'fees.activityFee': 'Activity Fee',
    'fees.lateFee': 'Late Fee',
    'fees.discount': 'Discount',
    'fees.scholarship': 'Scholarship',
    'fees.paymentHistory': 'Payment History',
    'fees.paymentMethod': 'Payment Method',
    'fees.transactionId': 'Transaction ID',
    'fees.receiptNumber': 'Receipt Number',
    'fees.dueDate': 'Due Date',
    'fees.paymentDate': 'Payment Date',
    'fees.amountPaid': 'Amount Paid',
    'fees.balanceAmount': 'Balance Amount',
    'fees.installments': 'Installments',
    'fees.feeWaiver': 'Fee Waiver',
    'fees.concession': 'Concession',
    
    // Activities & Events
    'activities.recentActivities': 'Recent Activities',
    'activities.upcomingEvents': 'Upcoming Events',
    'activities.assignment': 'Assignment',
    'activities.exam': 'Exam',
    'activities.fee': 'Fee',
    'activities.event': 'Event',
    'activities.completed': 'Completed',
    'activities.pending': 'Pending',
    'activities.meeting': 'Meeting',
    
    // Profile & General
    'profile.student': 'Student',
    'profile.performance': 'Performance',
    'profile.overallGrade': 'Overall grade',
    'profile.thisMonth': 'This month',
    'profile.profileInformation': 'Profile Information',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.phoneNumber': 'Phone Number',
    'profile.bio': 'Bio',
    'profile.saveChanges': 'Save Changes',
    'profile.schoolInformation': 'School Information',
    'profile.schoolName': 'School Name',
    'profile.updateSchoolInfo': 'Update School Info',
    'profile.name': 'Name',
    'profile.role': 'Role',
    'profile.profileDescription': 'Your personal profile details.',
    
    // System Settings
    'system.systemPreferences': 'System Preferences',
    'system.timezone': 'Timezone',
    'system.dateFormat': 'Date Format',
    'system.saveSettings': 'Save Settings',
    'system.navigationSettings': 'Navigation Settings',
    'system.showInfrastructureMenu': 'Show Infrastructure Menu',
    'system.infrastructureToggleDesc': 'Toggle visibility of Infrastructure features (Transport, Library, Hostel, Health)',
    'system.dataManagement': 'Data Management',
    'system.exportData': 'Export Data',
    'system.backupData': 'Backup Data',
    'system.downloadAllData': 'Download all school data',
    'system.createBackup': 'Create a backup of all data',
    'system.export': 'Export',
    'system.backup': 'Backup',
    
    // Notifications & Security
    'notifications.notificationPreferences': 'Notification Preferences',
    'notifications.emailNotifications': 'Email Notifications',
    'notifications.smsNotifications': 'SMS Notifications',
    'notifications.pushNotifications': 'Push Notifications',
    'notifications.receiveEmailUpdates': 'Receive updates via email',
    'notifications.receiveSmsUpdates': 'Receive updates via SMS',
    'notifications.receivePushUpdates': 'Receive browser notifications',
    'notifications.savePreferences': 'Save Preferences',
    'notifications.title': 'Notifications',
    
    'security.passwordSecurity': 'Password & Security',
    'security.currentPassword': 'Current Password',
    'security.newPassword': 'New Password',
    'security.confirmPassword': 'Confirm New Password',
    'security.changePassword': 'Change Password',
    'security.twoFactorAuth': 'Two-Factor Authentication',
    'security.enable2FA': 'Enable 2FA',
    'security.extraSecurity': 'Add an extra layer of security to your account',
    'security.configure': 'Configure',
    
    // Examinations & Results
    'examinations.title': 'Examinations',
    'examinations.createExam': 'Create Exam',
    'examinations.examSchedule': 'Exam Schedule',
    'examinations.examType': 'Exam Type',
    'examinations.markEntry': 'Mark Entry',
    'examinations.gradeEntry': 'Grade Entry',
    'examinations.resultGeneration': 'Result Generation',
    'examinations.reportCard': 'Report Card',
    'examinations.transcript': 'Transcript',
    'examinations.hallTicket': 'Hall Ticket',
    'examinations.seatingArrangement': 'Seating Arrangement',
    'examinations.supervisorAssignment': 'Supervisor Assignment',
    'examinations.examStatistics': 'Exam Statistics',
    'examinations.toppers': 'Toppers',
    'examinations.failedStudents': 'Failed Students',
    'examinations.improvementExam': 'Improvement Exam',
    'examinations.supplementaryExam': 'Supplementary Exam',
    
    // Documents & Certificates
    'documents.title': 'Documents',
    'documents.certificates': 'Certificates',
    'documents.bonafideCertificate': 'Bonafide Certificate',
    'documents.transferCertificate': 'Transfer Certificate',
    'documents.characterCertificate': 'Character Certificate',
    'documents.experienceCertificate': 'Experience Certificate',
    'documents.salaryCertificate': 'Salary Certificate',
    'documents.markSheet': 'Mark Sheet',
    'documents.transcript': 'Transcript',
    'documents.progressReport': 'Progress Report',
    'documents.studentIdCard': 'Student ID Card',
    'documents.staffIdCard': 'Staff ID Card',
    'documents.libraryCard': 'Library Card',
    'documents.busPass': 'Bus Pass',
    'documents.feeReceipt': 'Fee Receipt',
    'documents.admissionForm': 'Admission Form',
    
    // Library Management
    'library.title': 'Library Management',
    'library.bookManagement': 'Book Management',
    'library.bookIssue': 'Book Issue',
    'library.bookReturn': 'Book Return',
    'library.bookReservation': 'Book Reservation',
    'library.overdueBooks': 'Overdue Books',
    'library.fineManagement': 'Fine Management',
    'library.libraryCard': 'Library Card',
    'library.bookCatalog': 'Book Catalog',
    'library.authorWise': 'Author Wise',
    'library.subjectWise': 'Subject Wise',
    'library.publisherWise': 'Publisher Wise',
    'library.digitalLibrary': 'Digital Library',
    'library.eBooks': 'E-Books',
    'library.journals': 'Journals',
    'library.magazines': 'Magazines',
    'library.newspapers': 'Newspapers',
    
    // Transport Management
    'transport.title': 'Transport Management',
    'transport.busManagement': 'Bus Management',
    'transport.routeManagement': 'Route Management',
    'transport.driverManagement': 'Driver Management',
    'transport.studentAllocation': 'Student Allocation',
    'transport.feeCollection': 'Fee Collection',
    'transport.gpsTracking': 'GPS Tracking',
    'transport.maintenanceSchedule': 'Maintenance Schedule',
    'transport.fuelManagement': 'Fuel Management',
    'transport.incidentReporting': 'Incident Reporting',
    'transport.emergencyContact': 'Emergency Contact',
    'transport.routeOptimization': 'Route Optimization',
    'transport.vehicleInspection': 'Vehicle Inspection',
    
    // Health Management  
    'health.title': 'Health Management',
    'health.healthCheckup': 'Health Checkup',
    'health.medicalRecord': 'Medical Record',
    'health.vaccination': 'Vaccination',
    'health.firstAid': 'First Aid',
    'health.healthCard': 'Health Card',
    'health.BMITracking': 'BMI Tracking',
    'health.visionTesting': 'Vision Testing',
    'health.dentalCheckup': 'Dental Checkup',
    'health.healthInsurance': 'Health Insurance',
    'health.emergencyMedical': 'Emergency Medical',
    'health.nutritionPlan': 'Nutrition Plan',
    'health.mentalHealth': 'Mental Health',
    'health.counseling': 'Counseling',
    
    // Hostel Management
    'hostel.title': 'Hostel Management',
    'hostel.roomAllocation': 'Room Allocation',
    'hostel.feeManagement': 'Fee Management',
    'hostel.messManagement': 'Mess Management',
    'hostel.attendanceTracking': 'Attendance Tracking',
    'hostel.visitorManagement': 'Visitor Management',
    'hostel.complaintManagement': 'Complaint Management',
    'hostel.maintenanceRequest': 'Maintenance Request',
    'hostel.securityManagement': 'Security Management',
    'hostel.inventoryManagement': 'Inventory Management',
    'hostel.studentWelfare': 'Student Welfare',
    'hostel.roomInspection': 'Room Inspection',
    'hostel.leaveManagement': 'Leave Management',
    
    // Visitor Management
    'visitor.title': 'Visitor Management',
    'visitor.register': 'Register Visitor',
    'visitor.active': 'Active Visitors',
    'visitor.history': 'Visitor History',
    'visitor.analytics': 'Analytics',
    'visitor.checkIn': 'Check In',
    'visitor.checkOut': 'Check Out',
    'visitor.name': 'Visitor Name',
    'visitor.phone': 'Phone Number',
    'visitor.purpose': 'Purpose of Visit',
    'visitor.personToMeet': 'Person to Meet',
    'visitor.idProof': 'ID Proof Type',
    'visitor.idNumber': 'ID Number',
    'visitor.timeIn': 'Time In',
    'visitor.timeOut': 'Time Out',
    'visitor.status': 'Status',
    'visitor.actions': 'Actions',
    'visitor.totalVisitors': 'Total Visitors',
    'visitor.checkInTime': 'Check In Time',
    'visitor.checkOutTime': 'Check Out Time',
    
    // Student Profile Labels
    'student.profile': 'Student Profile',
    'student.completeInfo': 'Complete student information and records',
    'student.back': 'Back',
    'student.editProfile': 'Edit Profile',
    'student.deactivate': 'Deactivate',
    'student.reactivate': 'Reactivate',
    'student.uploadPhoto': 'Upload Recent Photo',
    'student.personalDetails': 'Personal Details',
    'student.rollNo': 'Roll No',
    'student.dateOfBirth': 'Date of Birth',
    'student.category': 'Category',
    'student.academicDetails': 'Academic Details',
    'student.classSection': 'Class & Section',
    'student.admissionDate': 'Admission Date',
    'student.previousSchool': 'Previous School',
    'student.guardianDetails': 'Guardian Details',
    'student.guardianName': 'Guardian Name',
    'student.attendance': 'Attendance',
    'student.academicPerformance': 'Academic Performance',
    'student.communication': 'Communication',
    'student.documents': 'Documents',
    'student.awards': 'Awards & Achievements',
    'student.fee': 'Fee',
    'student.feeInfo': 'Fee Information & Payment',
    'student.date': 'Date',
    'student.status': 'Status',
    'student.subject': 'Subject',
    'student.comment': 'Comment',
    'student.method': 'Method',
    'student.marks': 'Marks',
    'student.total': 'Total',
    'student.grade': 'Grade',
    'student.percentage': 'Percentage',
    'student.present': 'Present',
    'student.absent': 'Absent',
    'student.late': 'Late',
    'student.manual': 'Manual',
    'student.biometric': 'Biometric',
    'student.marksObtained': 'Marks Obtained',
    
    // Staff Profile Labels (unique ones only)
    'staff.profile': 'Staff Profile',
    'staff.completeInfo': 'Complete staff information and records',
    'staff.email': 'Email',
    'staff.phone': 'Phone',
    'staff.address': 'Address',
    'staff.classes': 'Classes',
    'staff.payroll': 'Payroll',
    'staff.performance': 'Performance',
    'staff.teachers': 'Teachers',
    
    // Student Management
    'studentMgmt.title': 'Student Management',
    'studentMgmt.subtitle': 'Manage student records and information',
    'studentMgmt.addStudent': 'Add Student',
    'studentMgmt.editStudent': 'Edit Student',
    'studentMgmt.totalStudents': 'Total Students',
    'studentMgmt.classes': 'Classes',
    
    // Staff Management
    'staffMgmt.title': 'Staff Management',
    'staffMgmt.subtitle': 'Manage school staff and faculty',
    'staffMgmt.addStaff': 'Add Staff',
    'staffMgmt.searchPlaceholder': 'Search by name, email, or ID...',
    'staffMgmt.filterDepartment': 'Filter by department',
    'staffMgmt.allDepartments': 'All Departments',
    
    // Parent Child Selector
    'parent.selectChild': 'Select Child',
    'parent.chooseChild': 'Choose which child\'s information to view',
    'parent.selectPlaceholder': 'Select a child',
    
    // Child Profile
    'child.overview': 'Overview',
    'child.subjects': 'Subjects',
    'child.recentGrades': 'Recent Grades',
    'child.profileDetails': 'Profile Details',
    'child.academicPerformance': 'Academic Performance',
    'child.upcomingEvents': 'Upcoming Events',
    'child.personalInfo': 'Personal Information',
    'child.contactInfo': 'Contact Information',
    'child.editContact': 'Edit Contact Info',
  },
  hi: {
    // Navigation  
    'nav.dashboard': 'डैशबोर्ड',
    'nav.students': 'छात्र',
    'nav.staff': 'कर्मचारी',
    'nav.academics': 'शैक्षणिक',
    'nav.attendance': 'उपस्थिति',
    'nav.fees': 'फीस',
    'nav.examinations': 'परीक्षा',
    'nav.documents': 'दस्तावेज़',
    'nav.idCards': 'पहचान पत्र',
    'nav.library': 'पुस्तकालय',
    'nav.health': 'स्वास्थ्य',
    'nav.hostel': 'छात्रावास',
    'nav.transport': 'परिवहन',
    'nav.timetable': 'समय सारणी',
    'nav.communication': 'संचार',
    'nav.announcements': 'घोषणाएं',
    'nav.admissions': 'प्रवेश',
    'nav.reports': 'रिपोर्ट',
    'nav.analytics': 'विश्लेषण',
    'nav.settings': 'सेटिंग्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.account': 'खाता',
    'nav.billing': 'बिलिंग',
    'nav.logout': 'लॉगआउट',
    'nav.myClasses': 'मेरी कक्षाएं',
    'nav.leaveManagement': 'छुट्टी प्रबंधन',
    'nav.childProfile': 'बच्चे की प्रोफ़ाइल',
    'nav.notifications': 'सूचनाएं',
    'nav.infrastructure': 'बुनियादी ढांचा',
    'nav.alumni': 'पूर्व छात्र',
    'nav.visitorManagement': 'आगंतुक प्रबंधन',
    'nav.wallet': 'वॉलेट',
    'nav.schoolConnect': 'स्कूल कनेक्ट',
    'nav.preferences': 'प्राथमिकताएं',
    'nav.preferencesDesc': 'अपनी व्यक्तिगत प्राथमिकताओं और उपस्थिति को अनुकूलित करें।',
    'nav.permissionsManager': 'अनुमति प्रबंधक',
    
    // Login & Auth
    'auth.signIn': 'साइन इन',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.enterCredentials': 'सिस्टम तक पहुंचने के लिए अपनी साख दर्ज करें',
    'auth.demoCredentials': 'डेमो साख (उपयोग करने के लिए क्लिक करें)',
    'auth.allDemoPassword': 'सभी डेमो खाते पासवर्ड का उपयोग करते हैं: "password"',
    'auth.superAdminAccess': 'सुपर एडमिन एक्सेस →',
    'auth.welcome': 'में आपका स्वागत है',
    'auth.signInAccess': 'अपने डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
    'auth.enterPassword': 'अपना पासवर्ड दर्ज करें',
    'auth.emailPlaceholder': 'your.email@school.edu',
    
    // Dashboard
    'dashboard.welcome': 'विटाना स्कूल प्रबंधन में आपका स्वागत है',
    'dashboard.welcomeBack': 'वापसी पर स्वागत है',
    'dashboard.welcomeUser': 'स्वागत है',
    'dashboard.totalStudents': 'कुल छात्र',
    'dashboard.totalStaff': 'कुल कर्मचारी',
    'dashboard.todayAttendance': 'आज की उपस्थिति',
    'dashboard.pendingFees': 'बकाया फीस',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.upcomingEvents': 'आगामी कार्यक्रम',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    'dashboard.myAssignedClasses': 'मेरी निर्दिष्ट कक्षाएं',
    'dashboard.classesToday': 'आज की कक्षाएं',
    'dashboard.studentHighlights': 'छात्र हाइलाइट्स',
    'dashboard.messages': 'संदेश',
    'dashboard.applyLeave': 'छुट्टी आवेदन',
    'dashboard.myClasses': 'मेरी कक्षाएं',
    'dashboard.gradeAssignments': 'असाइनमेंट ग्रेड करें',
    'dashboard.sendMessage': 'संदेश भेजें',
    'dashboard.trackProgress': 'अपने बच्चे की शैक्षणिक प्रगति और स्कूली गतिविधियों को ट्रैक करें।',
    'dashboard.teachingSchedule': 'आज के लिए आपका शिक्षण कार्यक्रम और महत्वपूर्ण अपडेट।',
    'dashboard.recentGrades': 'हाल के ग्रेड',
    'dashboard.achievementsTitle': 'उपलब्धियां',
    'dashboard.contactClassTeacher': 'क्लास टीचर से संपर्क करें',
    'dashboard.attendance': 'उपस्थिति',
    'dashboard.lastExamGrade': 'अंतिम परीक्षा ग्रेड',
    'dashboard.unreadMessages': 'अपठित संदेश',
    'dashboard.scheduled': 'निर्धारित',
    'dashboard.thisWeek': 'इस सप्ताह',
    'dashboard.thisMonth': 'इस महीने',
    'dashboard.improvement': 'सुधार',
    'dashboard.newToday': 'आज नया',
    'dashboard.achievementsCount': 'उपलब्धियां',
    'dashboard.unread': 'अपठित',
    'dashboard.dueDate': 'देय तिथि: 30वीं',
    'dashboard.active': 'सक्रिय',
    
    // Common
    'common.search': 'खोजें',
    'common.add': 'जोड़ें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.submit': 'जमा करें',
    'common.name': 'नाम',
    'common.email': 'ईमेल',
    'common.phone': 'फ़ोन',
    'common.address': 'पता',
    'common.status': 'स्थिति',
    'common.actions': 'कार्य',
    'common.date': 'दिनांक',
    'common.class': 'कक्षा',
    'common.section': 'अनुभाग',
    'common.subject': 'विषय',
    'common.view': 'देखें',
    'common.download': 'डाउनलोड',
    'common.print': 'प्रिंट',
    'common.export': 'निर्यात',
    'common.import': 'आयात',
    'common.filter': 'फ़िल्टर',
    'common.total': 'कुल',
    'common.active': 'सक्रिय',
    'common.inactive': 'निष्क्रिय',
    'common.loading': 'लोड हो रहा है...',
    'common.noData': 'कोई डेटा उपलब्ध नहीं',
    'common.close': 'बंद करें',
    'common.manage': 'प्रबंधित करें',
    'common.back': 'वापस',
    'common.deactivate': 'निष्क्रिय करें',
    'common.reactivate': 'पुनः सक्रिय करें',
    'common.reason': 'कारण',
    'common.uploadPhoto': 'फोटो अपलोड करें',
    'common.warning': 'चेतावनी',
    'common.generateTC': 'TC जनरेट करें',
    'common.reportCard': 'रिपोर्ट कार्ड',
    'common.preview': 'पूर्वावलोकन',
    'common.previewDesc': 'प्रिंट या डाउनलोड करने से पहले दस्तावेज़ का पूर्वावलोकन करें',
    'common.permissions': 'अनुमतियां',
    'common.store': 'स्टोर',
    'common.inventory': 'सूची',
    'common.sales': 'बिक्री',
    'common.lowStock': 'कम स्टॉक',
    
    // Permissions Manager
    'permissions.title': 'अनुमति प्रबंधक',
    'permissions.description': 'पहुंच अनुमतियां और भूमिकाओं को प्रबंधित करें',
    'permissions.moduleAccess': 'मॉड्यूल पहुंच',
    'permissions.roleManagement': 'भूमिका प्रबंधन',
    'permissions.module': 'मॉड्यूल',
    'permissions.enabled': 'सक्षम',
    'permissions.disabled': 'अक्षम',
    'permissions.read': 'देखें',
    'permissions.write': 'संपादित करें',
    'permissions.delete': 'हटाएं',
    'permissions.saveChanges': 'परिवर्तन सहेजें',
    'permissions.success': 'सफलता',
    'permissions.updated': 'अनुमतियां सफलतापूर्वक अपडेट की गईं',
    'permissions.error': 'त्रुटि',
    'permissions.updateFailed': 'अनुमतियां अपडेट करने में विफल',
    'permissions.noChanges': 'सहेजने के लिए कोई परिवर्तन नहीं',
    'permissions.viewAccess': 'पहुंच देखें',
    'permissions.editAccess': 'पहुंच संपादित करें',
    'permissions.deleteAccess': 'पहुंच हटाएं',
    
    // Store Manager
    'store.title': 'स्टोर प्रबंधन',
    'store.description': 'इन्वेंटरी, बिक्री और स्टोर संचालन प्रबंधित करें',
    'store.inventory': 'सूची',
    'store.sales': 'बिक्री',
    'store.lowStock': 'कम स्टॉक अलर्ट',
    'store.addItem': 'वस्तु जोड़ें',
    'store.addSale': 'बिक्री जोड़ें',
    'store.itemName': 'वस्तु का नाम',
    'store.category': 'श्रेणी',
    'store.price': 'मूल्य',
    'store.stock': 'स्टॉक',
    'store.reorderLevel': 'पुनर्व्यवस्था स्तर',
    'store.sku': 'एसकेयू',
    'store.totalValue': 'कुल इन्वेंटरी मूल्य',
    'store.totalSales': 'कुल बिक्री',
    'store.lowStockItems': 'कम स्टॉक वस्तुएं',
    'store.searchItems': 'वस्तुएं खोजें...',
    'store.allCategories': 'सभी श्रेणियां',
    'store.uniform': 'वर्दी',
    'store.books': 'किताबें',
    'store.stationery': 'स्टेशनरी',
    'store.quantity': 'मात्रा',
    'store.paymentMethod': 'भुगतान विधि',
    'store.cash': 'नकद',
    'store.card': 'कार्ड',
    'store.upi': 'यूपीआई',
    'store.customerName': 'ग्राहक का नाम',
    'store.customerPhone': 'ग्राहक फ़ोन',
    'store.saleDate': 'बिक्री तिथि',
    'store.items': 'वस्तुएं',
    'store.total': 'कुल',
    'store.viewReceipt': 'रसीद देखें',
    'store.editSale': 'बिक्री संपादित करें',
    'store.deleteSale': 'बिक्री हटाएं',
    'store.saleAdded': 'बिक्री सफलतापूर्वक जोड़ी गई',
    'store.itemAdded': 'वस्तु सफलतापूर्वक जोड़ी गई',
    'store.itemUpdated': 'वस्तु सफलतापूर्वक अपडेट की गई',
    'store.itemDeleted': 'वस्तु सफलतापूर्वक हटाई गई',
    
    // Student Profile Page
    'studentProfilePage.title': 'छात्र प्रोफ़ाइल',
    'studentProfilePage.completeInfo': 'संपूर्ण छात्र जानकारी और रिकॉर्ड',
    'studentProfilePage.back': 'वापस',
    'studentProfilePage.editProfile': 'प्रोफ़ाइल संपादित करें',
    'studentProfilePage.deactivate': 'निष्क्रिय करें',
    'studentProfilePage.reactivate': 'पुनः सक्रिय करें',
    'studentProfilePage.personalDetails': 'व्यक्तिगत विवरण',
    'studentProfilePage.academicDetails': 'शैक्षणिक विवरण',
    'studentProfilePage.guardianDetails': 'अभिभावक विवरण',
    'studentProfilePage.uploadPhoto': 'हाल की फ़ोटो अपलोड करें',
    'studentProfilePage.rollNo': 'रोल नंबर',
    'studentProfilePage.dateOfBirth': 'जन्म तिथि',
    'studentProfilePage.category': 'श्रेणी',
    'studentProfilePage.classSection': 'कक्षा और अनुभाग',
    'studentProfilePage.admissionDate': 'प्रवेश तिथि',
    'studentProfilePage.previousSchool': 'पूर्व स्कूल',
    'studentProfilePage.guardianName': 'अभिभावक का नाम',
    'studentProfilePage.loadingProfile': 'छात्र प्रोफ़ाइल लोड हो रहा है...',
    'studentProfilePage.studentNotFound': 'छात्र नहीं मिला',
    'studentProfilePage.backToStudents': 'छात्रों पर वापस जाएं',
    'studentProfilePage.photoUpdated': 'फ़ोटो अपडेट की गई',
    'studentProfilePage.photoSavedSuccess': 'छात्र फ़ोटो सफलतापूर्वक सहेजी गई',
    'studentProfilePage.uploadFailed': 'अपलोड विफल',
    'studentProfilePage.couldNotSavePhoto': 'फ़ोटो सहेज नहीं सका',
    'studentProfilePage.successTitle': 'सफलता',
    'studentProfilePage.errorTitle': 'त्रुटि',
    'studentProfilePage.failedToLoad': 'छात्र प्रोफ़ाइल लोड करने में विफल',
    'studentProfilePage.deactivatedSuccess': 'छात्र सफलतापूर्वक निष्क्रिय',
    'studentProfilePage.reactivatedSuccess': 'छात्र सफलतापूर्वक पुनः सक्रिय',
    'studentProfilePage.failedToUpdate': 'छात्र स्थिति अपडेट करने में विफल',
    'studentProfilePage.attendance': 'उपस्थिति',
    'studentProfilePage.academicPerformance': 'शैक्षणिक प्रदर्शन',
    'studentProfilePage.communication': 'संचार',
    'studentProfilePage.documents': 'दस्तावेज़',
    'studentProfilePage.awards': 'पुरस्कार और उपलब्धियाँ',
    'studentProfilePage.fee': 'शुल्क',

    // Staff Profile Page
    'staffProfilePage.title': 'कर्मचारी प्रोफ़ाइल',
    'staffProfilePage.completeInfo': 'संपूर्ण कर्मचारी जानकारी और रिकॉर्ड',
    'staffProfilePage.back': 'वापस',
    'staffProfilePage.editProfile': 'प्रोफ़ाइल संपादित करें',
    'staffProfilePage.deactivate': 'निष्क्रिय करें',
    'staffProfilePage.reactivate': 'पुनः सक्रिय करें',
    'staffProfilePage.personalDetails': 'व्यक्तिगत विवरण',
    'staffProfilePage.professionalDetails': 'व्यावसायिक विवरण',
    'staffProfilePage.contactInfo': 'संपर्क जानकारी',
    'staffProfilePage.uploadPhoto': 'हाल की फ़ोटो अपलोड करें',
    'staffProfilePage.phone': 'फ़ोन',
    'staffProfilePage.email': 'ईमेल',
    'staffProfilePage.designation': 'पदनाम',
    'staffProfilePage.department': 'विभाग',
    'staffProfilePage.experience': 'अनुभव',
    'staffProfilePage.years': 'वर्ष',
    'staffProfilePage.address': 'पता',
    'staffProfilePage.emergencyContact': 'आपातकालीन संपर्क',
    'staffProfilePage.classes': 'कक्षाएं',
    'staffProfilePage.attendance': 'उपस्थिति',
    'staffProfilePage.payroll': 'वेतन',
    'staffProfilePage.documents': 'दस्तावेज़',
    'staffProfilePage.certificates': 'प्रमाणपत्र',
    'staffProfilePage.performance': 'प्रदर्शन',
    'staffProfilePage.assignedClasses': 'आवंटित कक्षाएं',
    'staffProfilePage.class': 'कक्षा',
    'staffProfilePage.subject': 'विषय',
    'staffProfilePage.students': 'छात्र',
    'staffProfilePage.viewDetails': 'विवरण देखें',
    'staffProfilePage.attendanceRecord': 'उपस्थिति रिकॉर्ड',
    'staffProfilePage.loadingProfile': 'कर्मचारी प्रोफ़ाइल लोड हो रहा है...',
    'staffProfilePage.staffNotFound': 'कर्मचारी नहीं मिला',
    'staffProfilePage.backToStaff': 'कर्मचारियों पर वापस जाएं',
    'staffProfilePage.photoUpdated': 'फ़ोटो अपडेट की गई',
    'staffProfilePage.photoSavedSuccess': 'कर्मचारी फ़ोटो सफलतापूर्वक सहेजी गई',
    'staffProfilePage.uploadFailed': 'अपलोड विफल',
    'staffProfilePage.couldNotSavePhoto': 'फ़ोटो सहेज नहीं सका',
    'staffProfilePage.successTitle': 'सफलता',
    'staffProfilePage.errorTitle': 'त्रुटि',
    'staffProfilePage.failedToLoad': 'कर्मचारी प्रोफ़ाइल लोड करने में विफल',
    'staffProfilePage.deactivatedSuccess': 'कर्मचारी सफलतापूर्वक निष्क्रिय',
    'staffProfilePage.reactivatedSuccess': 'कर्मचारी सफलतापूर्वक पुनः सक्रिय',
    'staffProfilePage.failedToUpdate': 'कर्मचारी स्थिति अपडेट करने में विफल',

    // Student Profile Drawer
    'studentProfile.title': 'छात्र प्रोफ़ाइल',
    'studentProfile.rollNo': 'रोल नंबर',
    'studentProfile.classSection': 'कक्षा और अनुभाग',
    'studentProfile.dob': 'जन्म तिथि',
    'studentProfile.guardian': 'अभिभावक',
    'studentProfile.guardianPhone': 'अभिभावक फोन',
    'studentProfile.address': 'पता',
    'studentProfile.category': 'श्रेणी',
    'studentProfile.admissionDate': 'प्रवेश तिथि',
    'studentProfile.previousSchool': 'पिछला स्कूल',
    'studentProfile.reactivateWarning': 'पुनः सक्रिय करने से छात्र को फिर से प्रवेश मिल जाएगा। क्या आप आगे बढ़ना चाहते हैं?',
    
    // Staff Profile
    'staffProfile.title': 'स्टाफ प्रोफ़ाइल',
    'staffProfile.designation': 'पदनाम',
    'staffProfile.department': 'विभाग',
    'staffProfile.subjects': 'विषय',
    'staffProfile.joiningDate': 'ज्वाइनिंग तिथि',
    'staffProfile.contact': 'संपर्क',
    'staffProfile.phone': 'फोन',
    'staffProfile.email': 'ईमेल',
    'staffProfile.address': 'पता',
    'staffProfile.payroll': 'वेतन',
    'staffProfile.leaveManagement': 'अवकाश प्रबंधन',
    'staffProfile.performanceTracking': 'प्रदर्शन ट्रैकिंग',
    'staffProfile.classesAssigned': 'आवंटित कक्षाएं',
    'staffProfile.noPayrollRecords': 'कोई वेतन रिकॉर्ड नहीं।',
    'staffProfile.noLeaveRecords': 'कोई अवकाश रिकॉर्ड नहीं।',
    'staffProfile.noPerformanceRecords': 'कोई प्रदर्शन रिकॉर्ड नहीं।',
    'staffProfile.active': 'सक्रिय',
    'staffProfile.inactive': 'निष्क्रिय',
    'staffProfile.inactiveMessage': 'यह स्टाफ सदस्य वर्तमान में निष्क्रिय है।',
    
    // Payroll
    'payroll.month': 'महीना',
    'payroll.basic': 'मूल वेतन',
    'payroll.allowances': 'भत्ते',
    'payroll.deductions': 'कटौती',
    'payroll.netPay': 'नेट वेतन',
    'payroll.status': 'स्थिति',
    'payroll.pending': 'लंबित',
    'payroll.paid': 'भुगतान किया',
    'payroll.save': 'सहेजें',
    'payroll.saving': 'सहेज रहे हैं...',
    
    // Leave
    'leave.type': 'प्रकार',
    'leave.from': 'से',
    'leave.to': 'तक',
    'leave.status': 'स्थिति',
    'leave.reason': 'कारण',
    'leave.approved': 'स्वीकृत',
    'leave.rejected': 'अस्वीकृत',
    
    // Performance
    'performance.year': 'वर्ष',
    'performance.rating': 'रेटिंग',
    'performance.remarks': 'टिप्पणियां',
    
    // Student List
    'studentList.title': 'छात्र',
    'studentList.subtitle': 'छात्र सूचना और रिकॉर्ड प्रबंधित करें',
    'studentList.filters': 'फ़िल्टर और खोज',
    'studentList.searchPlaceholder': 'नाम या रोल नंबर से खोजें...',
    'studentList.allClasses': 'सभी कक्षाएं',
    'studentList.class': 'कक्षा',
    'studentList.allSections': 'सभी अनुभाग',
    'studentList.section': 'अनुभाग',
    'studentList.clearFilters': 'फ़िल्टर साफ़ करें',
    'studentList.showing': 'दिखा रहे हैं',
    'studentList.of': 'में से',
    'studentList.students': 'छात्र',
    'studentList.rollNo': 'रोल नंबर',
    'studentList.name': 'नाम',
    'studentList.guardianName': 'अभिभावक का नाम',
    'studentList.contact': 'संपर्क',
    'studentList.status': 'स्थिति',
    'studentList.actions': 'कार्रवाई',
    'studentList.loading': 'छात्र लोड हो रहे हैं...',
    'studentList.noStudentsFound': 'कोई छात्र नहीं मिला',
    'studentList.adjustCriteria': 'अपने खोज मानदंड को समायोजित करने का प्रयास करें',
    'studentList.addFirstStudent': 'पहला छात्र जोड़ें',
    
    // Staff List
    'staffList.title': 'स्टाफ प्रबंधन',
    'staffList.addStaff': 'स्टाफ जोड़ें',
    'staffList.directory': 'स्टाफ निर्देशिका',
    'staffList.searchPlaceholder': 'स्टाफ खोजें...',
    'staffList.filter': 'फ़िल्टर',
    'staffList.name': 'नाम',
    'staffList.designation': 'पदनाम',
    'staffList.department': 'विभाग',
    'staffList.contact': 'संपर्क',
    'staffList.status': 'स्थिति',
    'staffList.actions': 'कार्रवाई',
    'staffList.noStaffFound': 'कोई स्टाफ नहीं मिला।',
    
    // Child Profile
    'childProfile.title': 'मेरा बच्चा',
    'childProfile.studentId': 'छात्र आईडी',
    'childProfile.overallGrade': 'समग्र ग्रेड',
    'childProfile.attendance': 'उपस्थिति',
    'childProfile.overview': 'अवलोकन',
    'childProfile.subjects': 'विषय',
    'childProfile.recentGrades': 'हाल के ग्रेड',
    'childProfile.profileDetails': 'प्रोफ़ाइल विवरण',
    'childProfile.academicPerformance': 'शैक्षणिक प्रदर्शन',
    'childProfile.classRank': 'कक्षा रैंक',
    'childProfile.attendanceRate': 'उपस्थिति दर',
    'childProfile.thisWeek': 'इस सप्ताह',
    'childProfile.mathTest': 'गणित परीक्षा',
    'childProfile.tomorrow': 'कल',
    'childProfile.scienceProject': 'विज्ञान प्रोजेक्ट जमा',
    'childProfile.friday': 'शुक्रवार',
    'childProfile.ptMeeting': 'अभिभावक-शिक्षक बैठक',
    'childProfile.saturday': 'शनिवार',
    'childProfile.subjectPerformance': 'विषय प्रदर्शन',
    'childProfile.teacher': 'शिक्षक',
    'childProfile.currentGrade': 'वर्तमान ग्रेड',
    'childProfile.subject': 'विषय',
    'childProfile.assessment': 'मूल्यांकन',
    'childProfile.grade': 'ग्रेड',
    'childProfile.date': 'तिथि',
    'childProfile.studentProfile': 'छात्र प्रोफ़ाइल',
    'childProfile.editContactInfo': 'संपर्क जानकारी संपादित करें',
    'childProfile.editContactTitle': 'संपर्क जानकारी संपादित करें',
    'childProfile.phoneNumber': 'फोन नंबर',
    'childProfile.emailAddress': 'ईमेल पता',
    'childProfile.address': 'पता',
    'childProfile.updateContact': 'संपर्क जानकारी अपडेट करें',
    'childProfile.fullName': 'पूरा नाम',
    'childProfile.dateOfBirth': 'जन्म तिथि',
    'childProfile.bloodGroup': 'रक्त समूह',
    'childProfile.admissionDate': 'प्रवेश तिथि',
    'childProfile.contactInformation': 'संपर्क जानकारी',
    'childProfile.successTitle': 'सफलता',
    'childProfile.successMessage': 'संपर्क जानकारी सफलतापूर्वक अपडेट की गई',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.description': 'ऐप सेटिंग्स और प्राथमिकताएं।',
    'settings.theme': 'थीम',
    'settings.systemDefault': 'सिस्टम डिफ़ॉल्ट',
    'settings.enabled': 'सक्रिय',
    'settings.general': 'सामान्य',
    'settings.language': 'भाषा',
    'settings.selectLanguage': 'भाषा चुनें',
    'settings.english': 'English',
    'settings.hindi': 'हिंदी',
    'settings.selectTheme': 'थीम चुनें',
    'settings.light': 'हल्का',
    'settings.dark': 'गहरा',
    'settings.system': 'सिस्टम',
    'settings.notifications': 'अधिसूचनाएं',
    'settings.security': 'सुरक्षा',
    'settings.backup': 'बैकअप',
    'settings.biometric': 'बायोमेट्रिक प्रबंधन',
    'settings.import': 'डेटा आयात',
    
    // Students
    'students.title': 'छात्र प्रबंधन',
    'students.addStudent': 'छात्र जोड़ें',
    'students.studentList': 'छात्र सूची',
    'students.rollNo': 'रोल नंबर',
    'students.guardian': 'अभिभावक',
    'students.admissionDate': 'प्रवेश दिनांक',
    'students.totalStudents': 'कुल छात्र',
    'students.studentDetails': 'छात्र विवरण',
    'students.personalInfo': 'व्यक्तिगत जानकारी',
    'students.academicInfo': 'शैक्षणिक जानकारी',
    'students.contactInfo': 'संपर्क जानकारी',
    'students.emergencyContact': 'आपातकालीन संपर्क',
    'students.medicalInfo': 'चिकित्सा जानकारी',
    'students.transportInfo': 'परिवहन जानकारी',
    'students.feeStatus': 'फीस स्थिति',
    'students.attendanceRecord': 'उपस्थिति रिकॉर्ड',
    'students.examResults': 'परीक्षा परिणाम',
    'students.disciplinaryRecord': 'अनुशासनात्मक रिकॉर्ड',
    'students.achievements': 'उपलब्धियां',
    'students.documents': 'दस्तावेज़',
    'students.bloodGroup': 'रक्त समूह',
    'students.allergies': 'एलर्जी',
    'students.specialNeeds': 'विशेष आवश्यकताएं',
    'students.parentOccupation': 'माता-पिता का व्यवसाय',
    'students.annualIncome': 'वार्षिक आय',
    'students.caste': 'जाति',
    'students.religion': 'धर्म',
    'students.nationality': 'राष्ट्रीयता',
    
    // Staff
    'staff.title': 'कर्मचारी प्रबंधन',
    'staff.addStaff': 'कर्मचारी जोड़ें',
    'staff.staffList': 'कर्मचारी सूची',
    'staff.designation': 'पदनाम',
    'staff.department': 'विभाग',
    'staff.joiningDate': 'ज्वाइनिंग दिनांक',
    'staff.totalStaff': 'कुल कर्मचारी',
    'staff.staffDetails': 'कर्मचारी विवरण',
    'staff.personalInfo': 'व्यक्तिगत जानकारी',
    'staff.professionalInfo': 'व्यावसायिक जानकारी',
    'staff.contactInfo': 'संपर्क जानकारी',
    'staff.emergencyContact': 'आपातकालीन संपर्क',
    'staff.bankDetails': 'बैंक विवरण',
    'staff.qualifications': 'योग्यताएं',
    'staff.experience': 'अनुभव',
    'staff.salary': 'वेतन',
    'staff.allowances': 'भत्ते',
    'staff.deductions': 'कटौती',
    'staff.workingHours': 'कार्य घंटे',
    'staff.leaveBalance': 'छुट्टी शेष',
    'staff.performanceRating': 'प्रदर्शन रेटिंग',
    'staff.training': 'प्रशिक्षण',
    'staff.certifications': 'प्रमाणपत्र',
    'staff.employeeId': 'कर्मचारी आईडी',
    'staff.subjectsTaught': 'पढ़ाए गए विषय',
    'staff.classesAssigned': 'निर्दिष्ट कक्षाएं',
    'staff.teachingLoad': 'शिक्षण भार',
    'staff.extraCurricular': 'अतिरिक्त पाठ्यक्रम गतिविधियां',
    
    // Attendance
    'attendance.title': 'उपस्थिति प्रबंधन',
    'attendance.markAttendance': 'उपस्थिति चिह्नित करें',
    'attendance.present': 'उपस्थित',
    'attendance.absent': 'अनुपस्थित',
    'attendance.late': 'देर से',
    'attendance.excused': 'माफ़',
    'attendance.attendanceReport': 'उपस्थिति रिपोर्ट',
    
    // Academic
    'academic.title': 'शैक्षणिक प्रबंधन',
    'academic.academicYear': 'शैक्षणिक वर्ष',
    'academic.classes': 'कक्षाएं',
    'academic.subjects': 'विषय',
    'academic.syllabus': 'पाठ्यक्रम',
    'academic.results': 'परिणाम',
    
    // Fees & Payments
    'fees.title': 'फीस प्रबंधन',
    'fees.payNow': 'अभी भुगतान करें',
    'fees.feeSummary': 'फीस सारांश',
    'fees.totalFees': 'कुल फीस',
    'fees.pending': 'बकाया',
    'fees.nextDue': 'अगली देय तिथि',
    'fees.viewDetails': 'विवरण देखें',
    'fees.feeStructure': 'फीस संरचना',
    'fees.tuitionFee': 'ट्यूशन फीस',
    'fees.admissionFee': 'प्रवेश फीस',
    'fees.examFee': 'परीक्षा फीस',
    'fees.libraryFee': 'पुस्तकालय फीस',
    'fees.transportFee': 'परिवहन फीस',
    'fees.hostelFee': 'छात्रावास फीस',
    'fees.developmentFee': 'विकास फीस',
    'fees.activityFee': 'गतिविधि फीस',
    'fees.lateFee': 'विलंब शुल्क',
    'fees.discount': 'छूट',
    'fees.scholarship': 'छात्रवृत्ति',
    'fees.paymentHistory': 'भुगतान इतिहास',
    'fees.paymentMethod': 'भुगतान विधि',
    'fees.transactionId': 'लेन-देन आईडी',
    'fees.receiptNumber': 'रसीद संख्या',
    'fees.dueDate': 'देय तिथि',
    'fees.paymentDate': 'भुगतान दिनांक',
    'fees.amountPaid': 'भुगतान राशि',
    'fees.balanceAmount': 'शेष राशि',
    'fees.installments': 'किस्तें',
    'fees.feeWaiver': 'फीस माफी',
    'fees.concession': 'रियायत',
    
    // Activities & Events
    'activities.recentActivities': 'हाल की गतिविधियां',
    'activities.upcomingEvents': 'आगामी कार्यक्रम',
    'activities.assignment': 'असाइनमेंट',
    'activities.exam': 'परीक्षा',
    'activities.fee': 'फीस',
    'activities.event': 'कार्यक्रम',
    'activities.completed': 'पूर्ण',
    'activities.pending': 'बकाया',
    'activities.meeting': 'मीटिंग',
    
    // Profile & General
    'profile.student': 'छात्र',
    'profile.performance': 'प्रदर्शन',
    'profile.overallGrade': 'समग्र ग्रेड',
    'profile.thisMonth': 'इस महीने',
    'profile.profileInformation': 'प्रोफ़ाइल जानकारी',
    'profile.firstName': 'नाम',
    'profile.lastName': 'उपनाम',
    'profile.phoneNumber': 'फ़ोन नंबर',
    'profile.bio': 'बायो',
    'profile.saveChanges': 'परिवर्तन सेव करें',
    'profile.schoolInformation': 'स्कूल की जानकारी',
    'profile.schoolName': 'स्कूल का नाम',
    'profile.updateSchoolInfo': 'स्कूल की जानकारी अपडेट करें',
    'profile.name': 'नाम',
    'profile.role': 'भूमिका',
    'profile.profileDescription': 'आपकी व्यक्तिगत प्रोफ़ाइल विवरण।',
    
    // System Settings
    'system.systemPreferences': 'सिस्टम प्राथमिकताएं',
    'system.timezone': 'समय क्षेत्र',
    'system.dateFormat': 'दिनांक प्रारूप',
    'system.saveSettings': 'सेटिंग्स सेव करें',
    'system.navigationSettings': 'नेवीगेशन सेटिंग्स',
    'system.showInfrastructureMenu': 'बुनियादी ढांचा मेनू दिखाएं',
    'system.infrastructureToggleDesc': 'बुनियादी ढांचा सुविधाओं की दृश्यता टॉगल करें (परिवहन, पुस्तकालय, छात्रावास, स्वास्थ्य)',
    'system.dataManagement': 'डेटा प्रबंधन',
    'system.exportData': 'डेटा निर्यात',
    'system.backupData': 'डेटा बैकअप',
    'system.downloadAllData': 'सभी स्कूल डेटा डाउनलोड करें',
    'system.createBackup': 'सभी डेटा का बैकअप बनाएं',
    'system.export': 'निर्यात',
    'system.backup': 'बैकअप',
    
    // Notifications & Security
    'notifications.notificationPreferences': 'अधिसूचना प्राथमिकताएं',
    'notifications.emailNotifications': 'ईमेल अधिसूचनाएं',
    'notifications.smsNotifications': 'SMS अधिसूचनाएं',
    'notifications.pushNotifications': 'पुश अधिसूचनाएं',
    'notifications.receiveEmailUpdates': 'ईमेल के माध्यम से अपडेट प्राप्त करें',
    'notifications.receiveSmsUpdates': 'SMS के माध्यम से अपडेट प्राप्त करें',
    'notifications.receivePushUpdates': 'ब्राउज़र अधिसूचनाएं प्राप्त करें',
    'notifications.savePreferences': 'प्राथमिकताएं सेव करें',
    'notifications.title': 'अधिसूचनाएं',
    
    'security.passwordSecurity': 'पासवर्ड और सुरक्षा',
    'security.currentPassword': 'वर्तमान पासवर्ड',
    'security.newPassword': 'नया पासवर्ड',
    'security.confirmPassword': 'नया पासवर्ड पुष्टि करें',
    'security.changePassword': 'पासवर्ड बदलें',
    'security.twoFactorAuth': 'दो-कारक प्रमाणीकरण',
    'security.enable2FA': '2FA सक्षम करें',
    'security.extraSecurity': 'अपने खाते में सुरक्षा की एक अतिरिक्त परत जोड़ें',
    'security.configure': 'कॉन्फ़िगर करें',
    
    // Examinations & Results
    'examinations.title': 'परीक्षाएं',
    'examinations.createExam': 'परीक्षा बनाएं',
    'examinations.examSchedule': 'परीक्षा कार्यक्रम',
    'examinations.examType': 'परीक्षा प्रकार',
    'examinations.markEntry': 'अंक प्रविष्टि',
    'examinations.gradeEntry': 'ग्रेड प्रविष्टि',
    'examinations.resultGeneration': 'परिणाम निर्माण',
    'examinations.reportCard': 'रिपोर्ट कार्ड',
    'examinations.transcript': 'प्रतिलेख',
    'examinations.hallTicket': 'हॉल टिकट',
    'examinations.seatingArrangement': 'बैठक व्यवस्था',
    'examinations.supervisorAssignment': 'पर्यवेक्षक नियुक्ति',
    'examinations.examStatistics': 'परीक्षा आंकड़े',
    'examinations.toppers': 'शीर्षक धारक',
    'examinations.failedStudents': 'असफल छात्र',
    'examinations.improvementExam': 'सुधार परीक्षा',
    'examinations.supplementaryExam': 'पूरक परीक्षा',
    
    // Documents & Certificates
    'documents.title': 'दस्तावेज़',
    'documents.certificates': 'प्रमाणपत्र',
    'documents.bonafideCertificate': 'प्रामाणिक प्रमाणपत्र',
    'documents.transferCertificate': 'स्थानांतरण प्रमाणपत्र',
    'documents.characterCertificate': 'चरित्र प्रमाणपत्र',
    'documents.experienceCertificate': 'अनुभव प्रमाणपत्र',
    'documents.salaryCertificate': 'वेतन प्रमाणपत्र',
    'documents.markSheet': 'अंक पत्रक',
    'documents.transcript': 'प्रतिलेख',
    'documents.progressReport': 'प्रगति रिपोर्ट',
    'documents.studentIdCard': 'छात्र पहचान पत्र',
    'documents.staffIdCard': 'कर्मचारी पहचान पत्र',
    'documents.libraryCard': 'पुस्तकालय कार्ड',
    'documents.busPass': 'बस पास',
    'documents.feeReceipt': 'फीस रसीद',
    'documents.admissionForm': 'प्रवेश फॉर्म',
    
    // Library Management
    'library.title': 'पुस्तकालय प्रबंधन',
    'library.bookManagement': 'पुस्तक प्रबंधन',
    'library.bookIssue': 'पुस्तक जारी करना',
    'library.bookReturn': 'पुस्तक वापसी',
    'library.bookReservation': 'पुस्तक आरक्षण',
    'library.overdueBooks': 'अतिदेय पुस्तकें',
    'library.fineManagement': 'जुर्माना प्रबंधन',
    'library.libraryCard': 'पुस्तकालय कार्ड',
    'library.bookCatalog': 'पुस्तक कैटलॉग',
    'library.authorWise': 'लेखक के अनुसार',
    'library.subjectWise': 'विषय के अनुसार',
    'library.publisherWise': 'प्रकाशक के अनुसार',
    'library.digitalLibrary': 'डिजिटल पुस्तकालय',
    'library.eBooks': 'ई-पुस्तकें',
    'library.journals': 'जर्नल',
    'library.magazines': 'पत्रिकाएं',
    'library.newspapers': 'समाचार पत्र',
    
    // Transport Management
    'transport.title': 'परिवहन प्रबंधन',
    'transport.busManagement': 'बस प्रबंधन',
    'transport.routeManagement': 'मार्ग प्रबंधन',
    'transport.driverManagement': 'चालक प्रबंधन',
    'transport.studentAllocation': 'छात्र आवंटन',
    'transport.feeCollection': 'फीस संग्रह',
    'transport.gpsTracking': 'GPS ट्रैकिंग',
    'transport.maintenanceSchedule': 'रखरखाव अनुसूची',
    'transport.fuelManagement': 'ईंधन प्रबंधन',
    'transport.incidentReporting': 'घटना रिपोर्टिंग',
    'transport.emergencyContact': 'आपातकालीन संपर्क',
    'transport.routeOptimization': 'मार्ग अनुकूलन',
    'transport.vehicleInspection': 'वाहन निरीक्षण',
    
    // Health Management  
    'health.title': 'स्वास्थ्य प्रबंधन',
    'health.healthCheckup': 'स्वास्थ्य जांच',
    'health.medicalRecord': 'चिकित्सा रिकॉर्ड',
    'health.vaccination': 'टीकाकरण',
    'health.firstAid': 'प्राथमिक चिकित्सा',
    'health.healthCard': 'स्वास्थ्य कार्ड',
    'health.BMITracking': 'BMI ट्रैकिंग',
    'health.visionTesting': 'दृष्टि परीक्षण',
    'health.dentalCheckup': 'दंत जांच',
    'health.healthInsurance': 'स्वास्थ्य बीमा',
    'health.emergencyMedical': 'आपातकालीन चिकित्सा',
    'health.nutritionPlan': 'पोषण योजना',
    'health.mentalHealth': 'मानसिक स्वास्थ्य',
    'health.counseling': 'परामर्श',
    
    // Hostel Management
    'hostel.title': 'छात्रावास प्रबंधन',
    'hostel.roomAllocation': 'कमरा आवंटन',
    'hostel.feeManagement': 'फीस प्रबंधन',
    'hostel.messManagement': 'मेस प्रबंधन',
    'hostel.attendanceTracking': 'उपस्थिति ट्रैकिंग',
    'hostel.visitorManagement': 'आगंतुक प्रबंधन',
    'hostel.complaintManagement': 'शिकायत प्रबंधन',
    'hostel.maintenanceRequest': 'रखरखाव अनुरोध',
    'hostel.securityManagement': 'सुरक्षा प्रबंधन',
    'hostel.inventoryManagement': 'इन्वेंटरी प्रबंधन',
    'hostel.studentWelfare': 'छात्र कल्याण',
    'hostel.roomInspection': 'कमरा निरीक्षण',
    'hostel.leaveManagement': 'छुट्टी प्रबंधन',
    
    // Visitor Management
    'visitor.title': 'आगंतुक प्रबंधन',
    'visitor.register': 'आगंतुक पंजीकरण',
    'visitor.active': 'सक्रिय आगंतुक',
    'visitor.history': 'आगंतुक इतिहास',
    'visitor.analytics': 'विश्लेषण',
    'visitor.checkIn': 'चेक इन',
    'visitor.checkOut': 'चेक आउट',
    'visitor.name': 'आगंतुक का नाम',
    'visitor.phone': 'फोन नंबर',
    'visitor.purpose': 'भेंट का उद्देश्य',
    'visitor.personToMeet': 'मिलने वाला व्यक्ति',
    'visitor.idProof': 'पहचान पत्र प्रकार',
    'visitor.idNumber': 'पहचान पत्र संख्या',
    'visitor.timeIn': 'प्रवेश समय',
    'visitor.timeOut': 'निकास समय',
    'visitor.status': 'स्थिति',
    'visitor.actions': 'कार्रवाई',
    'visitor.totalVisitors': 'कुल आगंतुक',
    'visitor.checkInTime': 'चेक इन समय',
    'visitor.checkOutTime': 'चेक आउट समय',
    
    // Student Profile Labels
    'student.profile': 'छात्र प्रोफाइल',
    'student.completeInfo': 'संपूर्ण छात्र जानकारी और रिकॉर्ड',
    'student.back': 'वापस',
    'student.editProfile': 'प्रोफाइल संपादित करें',
    'student.deactivate': 'निष्क्रिय करें',
    'student.reactivate': 'पुनः सक्रिय करें',
    'student.uploadPhoto': 'हालिया फोटो अपलोड करें',
    'student.personalDetails': 'व्यक्तिगत विवरण',
    'student.rollNo': 'रोल नंबर',
    'student.dateOfBirth': 'जन्म तिथि',
    'student.category': 'श्रेणी',
    'student.academicDetails': 'शैक्षणिक विवरण',
    'student.classSection': 'कक्षा और अनुभाग',
    'student.admissionDate': 'प्रवेश तिथि',
    'student.previousSchool': 'पिछला स्कूल',
    'student.guardianDetails': 'अभिभावक विवरण',
    'student.guardianName': 'अभिभावक का नाम',
    'student.attendance': 'उपस्थिति',
    'student.academicPerformance': 'शैक्षणिक प्रदर्शन',
    'student.communication': 'संचार',
    'student.documents': 'दस्तावेज़',
    'student.awards': 'पुरस्कार और उपलब्धियां',
    'student.fee': 'शुल्क',
    'student.feeInfo': 'शुल्क जानकारी और भुगतान',
    'student.date': 'तारीख',
    'student.status': 'स्थिति',
    'student.subject': 'विषय',
    'student.comment': 'टिप्पणी',
    'student.method': 'विधि',
    'student.marks': 'अंक',
    'student.total': 'कुल',
    'student.grade': 'ग्रेड',
    'student.percentage': 'प्रतिशत',
    'student.present': 'उपस्थित',
    'student.absent': 'अनुपस्थित',
    'student.late': 'देर से',
    'student.manual': 'मैनुअल',
    'student.biometric': 'बायोमेट्रिक',
    'student.marksObtained': 'प्राप्त अंक',
    
    // Staff Profile Labels (unique ones only)
    'staff.profile': 'कर्मचारी प्रोफाइल',
    'staff.completeInfo': 'संपूर्ण कर्मचारी जानकारी और रिकॉर्ड',
    'staff.email': 'ईमेल',
    'staff.phone': 'फोन',
    'staff.address': 'पता',
    'staff.classes': 'कक्षाएं',
    'staff.payroll': 'वेतन',
    'staff.performance': 'प्रदर्शन',
    'staff.teachers': 'शिक्षक',
    
    // Student Management
    'studentMgmt.title': 'छात्र प्रबंधन',
    'studentMgmt.subtitle': 'छात्र रिकॉर्ड और जानकारी प्रबंधित करें',
    'studentMgmt.addStudent': 'छात्र जोड़ें',
    'studentMgmt.editStudent': 'छात्र संपादित करें',
    'studentMgmt.totalStudents': 'कुल छात्र',
    'studentMgmt.classes': 'कक्षाएं',
    
    // Staff Management
    'staffMgmt.title': 'कर्मचारी प्रबंधन',
    'staffMgmt.subtitle': 'स्कूल कर्मचारी और संकाय प्रबंधित करें',
    'staffMgmt.addStaff': 'कर्मचारी जोड़ें',
    'staffMgmt.searchPlaceholder': 'नाम, ईमेल या आईडी से खोजें...',
    'staffMgmt.filterDepartment': 'विभाग द्वारा फ़िल्टर करें',
    'staffMgmt.allDepartments': 'सभी विभाग',
    
    // Parent Child Selector
    'parent.selectChild': 'बच्चा चुनें',
    'parent.chooseChild': 'किस बच्चे की जानकारी देखनी है चुनें',
    'parent.selectPlaceholder': 'एक बच्चा चुनें',
    
    // Child Profile
    'child.overview': 'अवलोकन',
    'child.subjects': 'विषय',
    'child.recentGrades': 'हाल के ग्रेड',
    'child.profileDetails': 'प्रोफाइल विवरण',
    'child.academicPerformance': 'शैक्षणिक प्रदर्शन',
    'child.upcomingEvents': 'आगामी कार्यक्रम',
    'child.personalInfo': 'व्यक्तिगत जानकारी',
    'child.contactInfo': 'संपर्क जानकारी',
    'child.editContact': 'संपर्क जानकारी संपादित करें',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    // Force a re-render by dispatching a custom event
    window.dispatchEvent(new CustomEvent('languageChange', { detail: language }));
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}